/*
 * Copyright (C) Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package com.google.light.server.persistence.dao;

import com.google.light.server.dto.pojo.longwrapper.ModuleId;

import com.google.inject.Inject;
import com.google.light.server.dto.module.ModuleDto;
import com.google.light.server.persistence.entity.module.ModuleEntity;
import com.googlecode.objectify.Objectify;
import com.googlecode.objectify.ObjectifyService;
import java.util.logging.Logger;

/**
 * DAO for {@link ModuleEntity}.
 * 
 * @author Arjun Satyapal
 */
public class ModuleDao extends AbstractBasicDao<ModuleDto, ModuleEntity> {
  private static final Logger logger = Logger.getLogger(ModuleDao.class.getName());

  static {
    ObjectifyService.register(ModuleEntity.class);
  }

  @Inject
  public ModuleDao() {
    super(ModuleEntity.class);
  }

  /**
   * Put Module on datastore. Id for {@link ModuleEntity} is generated by DataStore.
   * 
   * {@inheritDoc}
   */
  @Override
  public ModuleEntity put(Objectify txn, ModuleEntity entity) {
    ModuleEntity returnEntity = super.put(txn, entity);
    String returnMsg = "Created/Updated ModuleEntity[" + returnEntity.getModuleId() + "].";

    return logAndReturn(logger, returnEntity, returnMsg);
  }

  /**
   * TODO(arjuns): Add test for this.
   * Fetch Module via ModuleId.
   */
  public ModuleEntity get(ModuleId moduleId) {
    return super.get(ModuleEntity.generateKey(moduleId));
  }
}
