/**
 * Configuration for dojo loader.
 * 
 * <p>Note that theses configurations are here to support 2 use cases:
 * <ul>
 * <li> Run tests on JSTestDriver with our dojoAmdPlugin</li>
 * <li> Run tests using the jasmine:bdd goal with jasmine-maven-plugin</li>
 * </ul>
 * 
 * In both cases, our project base directory
 * (the one with the pom.xml) is being served on the root of the server.
 * 
 */
var dojoConfig = {
  //'dojo-undef-api': true, 'dojo-publish-privates': true, 
  has: {'config-dojo-loader-catches': true},
  cacheBust:new Date(), // Needed to avoid some browsers from caching the code
  isDebug: true,
  deferredOnError: function(e) { console.log(e.message, e.stack) },
      packages: [ {
          name: 'light',
          location: '/src/main/webapp/js/light'
      }, {
          name: 'lightTest',
          location: '/src/test/webapp/jsTest/lightTest'
      },
      { name: "dojo", location: "/src/main/webapp/js/external/djk/dojo" },
      { name: "dijit", location: "/src/main/webapp/js/external/djk/dijit" },
      { name: "dojox", location: "/src/main/webapp/js/external/djk/dojox" }
      ]
};

/**
 * Configuration for the dojoAmdAdapter
 */
var dojoAmdAdapterConfig = {
    // Only the JSTestDriver adapter uses this. Jasmine Maven plugin automatically adds the files
    // This file is supposed to be generated by maven
    testListFile: "/src/test/webapp/jsTest/testList.js",
    testMidFormatter: function(mid) {
      if(mid.substr(mid.length-3) == ".js") {
        return mid.substr(0,mid.length-3);
      }
    }
};